version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/my-app
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: install.sh
      timeout: 300
      runas: ec2-user